name: FileHeron
description: A simple file server
version: 1.0.0
homepage: https://www.fileheron.com
repository: https://github.com/horizech/fileheron

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    fileheron_server: ^1.0.2
dev_dependencies:
